name: Ejercicio 2
on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 'latest'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Lanzar comando pytest
        run: pytest
