name: Ejercicio 2
on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: python-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Lanzar comando pytest
        run: pytest
